;;;; package.lisp

(uiop:define-package #:steam-audio
  (:use #:cl #:cffi-c-ref)
  (:export #:add-instanced-mesh
           #:add-probe-batch
           #:add-probe-to-batch
           #:apply-ambisonics-binaural-effect
           #:apply-ambisonics-panning-effect
           #:apply-binaural-effect
           #:apply-binaural-effect-with-parameters
           #:apply-direct-sound-effect
           #:apply-panning-effect
           #:apply-virtual-surround-effect
           #:bake-propagation
           #:bake-reverb
           #:bake-static-listener
           #:calculate-relative-direction
           #:cancel-bake
           #:cleanup
           #:commit-scene
           #:convert-audio-buffer-format
           #:create-ambisonics-binaural-effect
           #:create-ambisonics-panning-effect
           #:create-ambisonics-rotator
           #:create-binaural-effect
           #:create-binaural-renderer
           #:create-compute-device
           #:create-context
           #:ipl-create-context
           #:create-convolution-effect
           #:create-direct-sound-effect
           #:create-environment
           #:create-environmental-renderer
           #:create-instanced-mesh
           #:create-panning-effect
           #:create-probe-batch
           #:create-probe-box
           #:create-probe-manager
           #:create-scene
           #:create-static-mesh
           #:create-virtual-surround-effect
           #:deinterleave-audio-buffer
           #:delete-baked-data-by-identifier
           #:destroy-ambisonics-binaural-effect
           #:destroy-ambisonics-panning-effect
           #:destroy-ambisonics-rotator
           #:destroy-binaural-effect
           #:destroy-binaural-renderer
           #:destroy-compute-device
           #:destroy-context
           #:destroy-convolution-effect
           #:destroy-direct-sound-effect
           #:destroy-environment
           #:destroy-environmental-renderer
           #:destroy-instanced-mesh
           #:destroy-panning-effect
           #:destroy-probe-batch
           #:destroy-probe-box
           #:destroy-probe-manager
           #:destroy-scene
           #:destroy-static-mesh
           #:destroy-virtual-surround-effect
           #:finalize-probe-batch
           #:flush-ambisonics-binaural-effect
           #:flush-ambisonics-panning-effect
           #:flush-binaural-effect
           #:flush-convolution-effect
           #:flush-direct-sound-effect
           #:flush-panning-effect
           #:flush-virtual-surround-effect
           #:get-baked-data-size-by-identifier
           #:get-direct-sound-path
           #:get-environment-for-renderer
           #:get-mixed-environmental-audio
           #:get-probe-spheres
           #:get-wet-audio-for-convolution-effect
           #:interleave-audio-buffer
           #:load-probe-batch
           #:load-probe-box
           #:load-scene
           #:mix-audio-buffers
           #:remove-instanced-mesh
           #:remove-probe-batch
           #:rotate-ambisonics-audio-buffer
           #:save-probe-batch
           #:save-probe-box
           #:save-scene
           #:save-scene-as-obj
           #:set-ambisonics-rotation
           #:set-convolution-effect-identifier
           #:set-dry-audio-for-convolution-effect
           #:set-num-bounces
           #:update-instanced-mesh-transform))
