;;; This file was automatically generated by SWIG (http://www.swig.org).
;;; Version 3.0.12
;;;
;;; Do not make changes to this file unless you know what you are doing--modify
;;; the SWIG interface file instead.

(cffi:define-foreign-library phonon
  (:unix "libphonon.so")
  (:darwin "libphonon.dylib")
  (:cygwin "phonon.dll")
  (t (:default "libphonon")))
(cffi:use-foreign-library phonon)
(in-package :steam-audio/raw)



(alexandria:define-constant STEAMAUDIO_VERSION_MAJOR 2)

(alexandria:define-constant STEAMAUDIO_VERSION_MINOR 0)

(alexandria:define-constant STEAMAUDIO_VERSION_PATCH 18)

(cffi:defcenum IPLbool
  :IPL_FALSE
  :IPL_TRUE)

(cffi:defcenum IPLerror
  :IPL_STATUS_SUCCESS
  :IPL_STATUS_FAILURE
  :IPL_STATUS_OUTOFMEMORY
  :IPL_STATUS_INITIALIZATION)

(cffi:defcfun ("iplCreateContext" iplCreateContext) IPLerror
  (logCallback :pointer)
  (allocateCallback :pointer)
  (freeCallback :pointer)
  (context :pointer))

(cffi:defcfun ("iplDestroyContext" iplDestroyContext) :void
  (context :pointer))

(cffi:defcfun ("iplCleanup" iplCleanup) :void)

(cffi:defcstruct IPLVector3
  (x :float)
  (y :float)
  (z :float))

(cffi:defcstruct IPLBox
  (minCoordinates IPLVector3)
  (maxCoordinates IPLVector3))

(cffi:defcstruct IPLSphere
  (center IPLVector3)
  (radius :float))

(cffi:defcfun ("iplCalculateRelativeDirection" iplCalculateRelativeDirection) IPLVector3
  (sourcePosition IPLVector3)
  (listenerPosition IPLVector3)
  (listenerAhead IPLVector3)
  (listenerUp IPLVector3))

(cffi:defcenum IPLComputeDeviceType
  :IPL_COMPUTEDEVICE_CPU
  :IPL_COMPUTEDEVICE_GPU
  :IPL_COMPUTEDEVICE_ANY)

(cffi:defcstruct IPLComputeDeviceFilter
  (type IPLComputeDeviceType)
  (maxCUsToReserve :int)
  (fractionCUsForIRUpdate :float))

(cffi:defcfun ("iplCreateComputeDevice" iplCreateComputeDevice) IPLerror
  (context :pointer)
  (deviceFilter IPLComputeDeviceFilter)
  (device :pointer))

(cffi:defcfun ("iplDestroyComputeDevice" iplDestroyComputeDevice) :void
  (device :pointer))

(cffi:defcenum IPLSceneType
  :IPL_SCENETYPE_PHONON
  :IPL_SCENETYPE_EMBREE
  :IPL_SCENETYPE_RADEONRAYS
  :IPL_SCENETYPE_CUSTOM)

(cffi:defcenum IPLSimulationType
  :IPL_SIMTYPE_REALTIME
  :IPL_SIMTYPE_BAKED)

(cffi:defcstruct IPLSimulationSettings
  (sceneType IPLSceneType)
  (maxNumOcclusionSamples :int)
  (numRays :int)
  (numDiffuseSamples :int)
  (numBounces :int)
  (numThreads :int)
  (irDuration :float)
  (ambisonicsOrder :int)
  (maxConvolutionSources :int)
  (bakingBatchSize :int)
  (irradianceMinDistance :float))

(cffi:defcstruct IPLTriangle
  (indices :pointer :count 3))

(cffi:defcstruct IPLMaterial
  (lowFreqAbsorption :float)
  (midFreqAbsorption :float)
  (highFreqAbsorption :float)
  (scattering :float)
  (lowFreqTransmission :float)
  (midFreqTransmission :float)
  (highFreqTransmission :float))

(cffi:defcfun ("iplCreateScene" iplCreateScene) IPLerror
  (context :pointer)
  (computeDevice :pointer)
  (sceneType IPLSceneType)
  (numMaterials :int)
  (materials :pointer)
  (closestHitCallback :pointer)
  (anyHitCallback :pointer)
  (batchedClosestHitCallback :pointer)
  (batchedAnyHitCallback :pointer)
  (userData :pointer)
  (scene :pointer))

(cffi:defcfun ("iplDestroyScene" iplDestroyScene) :void
  (scene :pointer))

(cffi:defcfun ("iplCreateStaticMesh" iplCreateStaticMesh) IPLerror
  (scene :pointer)
  (numVertices :int)
  (numTriangles :int)
  (vertices :pointer)
  (triangles :pointer)
  (materialIndices :pointer)
  (staticMesh :pointer))

(cffi:defcfun ("iplDestroyStaticMesh" iplDestroyStaticMesh) :void
  (staticMesh :pointer))

(cffi:defcfun ("iplSaveScene" iplSaveScene) :int
  (scene :pointer)
  (data :pointer))

(cffi:defcfun ("iplLoadScene" iplLoadScene) IPLerror
  (context :pointer)
  (sceneType IPLSceneType)
  (data :pointer)
  (size :int)
  (computeDevice :pointer)
  (progressCallback :pointer)
  (scene :pointer))

(cffi:defcfun ("iplSaveSceneAsObj" iplSaveSceneAsObj) :void
  (scene :pointer)
  (fileBaseName :string))

(cffi:defcstruct IPLMatrix4x4
  (elements :pointer))

(cffi:defcfun ("iplCreateInstancedMesh" iplCreateInstancedMesh) IPLerror
  (scene :pointer)
  (instancedScene :pointer)
  (transform IPLMatrix4x4)
  (instancedMesh :pointer))

(cffi:defcfun ("iplDestroyInstancedMesh" iplDestroyInstancedMesh) :void
  (instancedMesh :pointer))

(cffi:defcfun ("iplAddInstancedMesh" iplAddInstancedMesh) :void
  (scene :pointer)
  (instancedMesh :pointer))

(cffi:defcfun ("iplRemoveInstancedMesh" iplRemoveInstancedMesh) :void
  (scene :pointer)
  (instancedMesh :pointer))

(cffi:defcfun ("iplUpdateInstancedMeshTransform" iplUpdateInstancedMeshTransform) :void
  (instancedMesh :pointer)
  (transform IPLMatrix4x4))

(cffi:defcfun ("iplCommitScene" iplCommitScene) :void
  (scene :pointer))

(cffi:defcfun ("iplCreateEnvironment" iplCreateEnvironment) IPLerror
  (context :pointer)
  (computeDevice :pointer)
  (simulationSettings IPLSimulationSettings)
  (scene :pointer)
  (probeManager :pointer)
  (environment :pointer))

(cffi:defcfun ("iplDestroyEnvironment" iplDestroyEnvironment) :void
  (environment :pointer))

(cffi:defcfun ("iplSetNumBounces" iplSetNumBounces) :void
  (environment :pointer)
  (numBounces :int))

(cffi:defcenum IPLConvolutionType
  :IPL_CONVOLUTIONTYPE_PHONON
  :IPL_CONVOLUTIONTYPE_TRUEAUDIONEXT)

(cffi:defcstruct IPLRenderingSettings
  (samplingRate :int)
  (frameSize :int)
  (convolutionType IPLConvolutionType))

(cffi:defcenum IPLChannelLayoutType
  :IPL_CHANNELLAYOUTTYPE_SPEAKERS
  :IPL_CHANNELLAYOUTTYPE_AMBISONICS)

(cffi:defcenum IPLChannelLayout
  :IPL_CHANNELLAYOUT_MONO
  :IPL_CHANNELLAYOUT_STEREO
  :IPL_CHANNELLAYOUT_QUADRAPHONIC
  :IPL_CHANNELLAYOUT_FIVEPOINTONE
  :IPL_CHANNELLAYOUT_SEVENPOINTONE
  :IPL_CHANNELLAYOUT_CUSTOM)

(cffi:defcenum IPLAmbisonicsOrdering
  :IPL_AMBISONICSORDERING_FURSEMALHAM
  :IPL_AMBISONICSORDERING_ACN)

(cffi:defcenum IPLAmbisonicsNormalization
  :IPL_AMBISONICSNORMALIZATION_FURSEMALHAM
  :IPL_AMBISONICSNORMALIZATION_SN3D
  :IPL_AMBISONICSNORMALIZATION_N3D)

(cffi:defcenum IPLChannelOrder
  :IPL_CHANNELORDER_INTERLEAVED
  :IPL_CHANNELORDER_DEINTERLEAVED)

(cffi:defcstruct IPLAudioFormat
  (channelLayoutType IPLChannelLayoutType)
  (channelLayout IPLChannelLayout)
  (numSpeakers :int)
  (speakerDirections :pointer)
  (ambisonicsOrder :int)
  (ambisonicsOrdering IPLAmbisonicsOrdering)
  (ambisonicsNormalization IPLAmbisonicsNormalization)
  (channelOrder IPLChannelOrder))

(cffi:defcstruct IPLAudioBuffer
  (format IPLAudioFormat)
  (numSamples :int)
  (interleavedBuffer :pointer)
  (deinterleavedBuffer :pointer))

(cffi:defcfun ("iplMixAudioBuffers" iplMixAudioBuffers) :void
  (numBuffers :int)
  (inputAudio :pointer)
  (outputAudio IPLAudioBuffer))

(cffi:defcfun ("iplInterleaveAudioBuffer" iplInterleaveAudioBuffer) :void
  (inputAudio IPLAudioBuffer)
  (outputAudio IPLAudioBuffer))

(cffi:defcfun ("iplDeinterleaveAudioBuffer" iplDeinterleaveAudioBuffer) :void
  (inputAudio IPLAudioBuffer)
  (outputAudio IPLAudioBuffer))

(cffi:defcfun ("iplConvertAudioBufferFormat" iplConvertAudioBufferFormat) :void
  (inputAudio IPLAudioBuffer)
  (outputAudio IPLAudioBuffer))

(cffi:defcfun ("iplCreateAmbisonicsRotator" iplCreateAmbisonicsRotator) IPLerror
  (context :pointer)
  (order :int)
  (rotator :pointer))

(cffi:defcfun ("iplDestroyAmbisonicsRotator" iplDestroyAmbisonicsRotator) :void
  (rotator :pointer))

(cffi:defcfun ("iplSetAmbisonicsRotation" iplSetAmbisonicsRotation) :void
  (rotator :pointer)
  (listenerAhead IPLVector3)
  (listenerUp IPLVector3))

(cffi:defcfun ("iplRotateAmbisonicsAudioBuffer" iplRotateAmbisonicsAudioBuffer) :void
  (rotator :pointer)
  (inputAudio IPLAudioBuffer)
  (outputAudio IPLAudioBuffer))

(cffi:defcenum IPLHrtfDatabaseType
  :IPL_HRTFDATABASETYPE_DEFAULT
  :IPL_HRTFDATABASETYPE_SOFA)

(cffi:defcstruct IPLHrtfParams
  (type IPLHrtfDatabaseType)
  (hrtfData :pointer)
  (sofaFileName :string))

(cffi:defcfun ("iplCreateBinauralRenderer" iplCreateBinauralRenderer) IPLerror
  (context :pointer)
  (renderingSettings IPLRenderingSettings)
  (params IPLHrtfParams)
  (renderer :pointer))

(cffi:defcfun ("iplDestroyBinauralRenderer" iplDestroyBinauralRenderer) :void
  (renderer :pointer))

(cffi:defcfun ("iplCreatePanningEffect" iplCreatePanningEffect) IPLerror
  (renderer :pointer)
  (inputFormat IPLAudioFormat)
  (outputFormat IPLAudioFormat)
  (effect :pointer))

(cffi:defcfun ("iplDestroyPanningEffect" iplDestroyPanningEffect) :void
  (effect :pointer))

(cffi:defcfun ("iplApplyPanningEffect" iplApplyPanningEffect) :void
  (effect :pointer)
  (binauralRenderer :pointer)
  (inputAudio IPLAudioBuffer)
  (direction IPLVector3)
  (outputAudio IPLAudioBuffer))

(cffi:defcfun ("iplFlushPanningEffect" iplFlushPanningEffect) :void
  (effect :pointer))

(cffi:defcenum IPLHrtfInterpolation
  :IPL_HRTFINTERPOLATION_NEAREST
  :IPL_HRTFINTERPOLATION_BILINEAR)

(cffi:defcfun ("iplCreateBinauralEffect" iplCreateBinauralEffect) IPLerror
  (renderer :pointer)
  (inputFormat IPLAudioFormat)
  (outputFormat IPLAudioFormat)
  (effect :pointer))

(cffi:defcfun ("iplDestroyBinauralEffect" iplDestroyBinauralEffect) :void
  (effect :pointer))

(cffi:defcfun ("iplApplyBinauralEffect" iplApplyBinauralEffect) :void
  (effect :pointer)
  (binauralRenderer :pointer)
  (inputAudio IPLAudioBuffer)
  (direction IPLVector3)
  (interpolation IPLHrtfInterpolation)
  (spatialBlend :float)
  (outputAudio IPLAudioBuffer))

(cffi:defcfun ("iplApplyBinauralEffectWithParameters" iplApplyBinauralEffectWithParameters) :void
  (effect :pointer)
  (binauralRenderer :pointer)
  (inputAudio IPLAudioBuffer)
  (direction IPLVector3)
  (interpolation IPLHrtfInterpolation)
  (enableSpatialBlend IPLbool)
  (spatialBlend :float)
  (outputAudio IPLAudioBuffer)
  (leftDelay :pointer)
  (rightDelay :pointer))

(cffi:defcfun ("iplFlushBinauralEffect" iplFlushBinauralEffect) :void
  (effect :pointer))

(cffi:defcfun ("iplCreateVirtualSurroundEffect" iplCreateVirtualSurroundEffect) IPLerror
  (renderer :pointer)
  (inputFormat IPLAudioFormat)
  (outputFormat IPLAudioFormat)
  (effect :pointer))

(cffi:defcfun ("iplDestroyVirtualSurroundEffect" iplDestroyVirtualSurroundEffect) :void
  (effect :pointer))

(cffi:defcfun ("iplApplyVirtualSurroundEffect" iplApplyVirtualSurroundEffect) :void
  (effect :pointer)
  (binauralRenderer :pointer)
  (inputAudio IPLAudioBuffer)
  (outputAudio IPLAudioBuffer))

(cffi:defcfun ("iplFlushVirtualSurroundEffect" iplFlushVirtualSurroundEffect) :void
  (effect :pointer))

(cffi:defcfun ("iplCreateAmbisonicsPanningEffect" iplCreateAmbisonicsPanningEffect) IPLerror
  (renderer :pointer)
  (inputFormat IPLAudioFormat)
  (outputFormat IPLAudioFormat)
  (effect :pointer))

(cffi:defcfun ("iplDestroyAmbisonicsPanningEffect" iplDestroyAmbisonicsPanningEffect) :void
  (effect :pointer))

(cffi:defcfun ("iplApplyAmbisonicsPanningEffect" iplApplyAmbisonicsPanningEffect) :void
  (effect :pointer)
  (binauralRenderer :pointer)
  (inputAudio IPLAudioBuffer)
  (outputAudio IPLAudioBuffer))

(cffi:defcfun ("iplFlushAmbisonicsPanningEffect" iplFlushAmbisonicsPanningEffect) :void
  (effect :pointer))

(cffi:defcfun ("iplCreateAmbisonicsBinauralEffect" iplCreateAmbisonicsBinauralEffect) IPLerror
  (renderer :pointer)
  (inputFormat IPLAudioFormat)
  (outputFormat IPLAudioFormat)
  (effect :pointer))

(cffi:defcfun ("iplDestroyAmbisonicsBinauralEffect" iplDestroyAmbisonicsBinauralEffect) :void
  (effect :pointer))

(cffi:defcfun ("iplApplyAmbisonicsBinauralEffect" iplApplyAmbisonicsBinauralEffect) :void
  (effect :pointer)
  (binauralRenderer :pointer)
  (inputAudio IPLAudioBuffer)
  (outputAudio IPLAudioBuffer))

(cffi:defcfun ("iplFlushAmbisonicsBinauralEffect" iplFlushAmbisonicsBinauralEffect) :void
  (effect :pointer))

(cffi:defcfun ("iplCreateEnvironmentalRenderer" iplCreateEnvironmentalRenderer) IPLerror
  (context :pointer)
  (environment :pointer)
  (renderingSettings IPLRenderingSettings)
  (outputFormat IPLAudioFormat)
  (threadCreateCallback :pointer)
  (threadDestroyCallback :pointer)
  (renderer :pointer))

(cffi:defcfun ("iplDestroyEnvironmentalRenderer" iplDestroyEnvironmentalRenderer) :void
  (renderer :pointer))

(cffi:defcfun ("iplGetEnvironmentForRenderer" iplGetEnvironmentForRenderer) :pointer
  (renderer :pointer))

(cffi:defcenum IPLDistanceAttenuationModelType
  :IPL_DISTANCEATTENUATION_DEFAULT
  :IPL_DISTANCEATTENUATION_INVERSEDISTANCE
  :IPL_DISTANCEATTENUATION_CALLBACK)

(cffi:defcstruct IPLDistanceAttenuationModel
  (type IPLDistanceAttenuationModelType)
  (minDistance :float)
  (callback :pointer)
  (userData :pointer)
  (dirty IPLbool))

(cffi:defcenum IPLAirAbsorptionModelType
  :IPL_AIRABSORPTION_DEFAULT
  :IPL_AIRABSORPTION_EXPONENTIAL
  :IPL_AIRABSORPTION_CALLBACK)

(cffi:defcstruct IPLAirAbsorptionModel
  (type IPLAirAbsorptionModelType)
  (coefficients :pointer :count 3)
  (callback :pointer)
  (userData :pointer)
  (dirty IPLbool))

(cffi:defcenum IPLDirectOcclusionMethod
  :IPL_DIRECTOCCLUSION_RAYCAST
  :IPL_DIRECTOCCLUSION_VOLUMETRIC)

(cffi:defcenum IPLDirectOcclusionMode
  :IPL_DIRECTOCCLUSION_NONE
  :IPL_DIRECTOCCLUSION_NOTRANSMISSION
  :IPL_DIRECTOCCLUSION_TRANSMISSIONBYVOLUME
  :IPL_DIRECTOCCLUSION_TRANSMISSIONBYFREQUENCY)

(cffi:defcstruct IPLDirectSoundPath
  (direction IPLVector3)
  (distanceAttenuation :float)
  (airAbsorption :pointer :count 3)
  (propagationDelay :float)
  (occlusionFactor :float)
  (transmissionFactor :pointer :count 3)
  (directivityFactor :float))

(cffi:defcstruct IPLDirectivity
  (dipoleWeight :float)
  (dipolePower :float)
  (callback :pointer)
  (userData :pointer))

(cffi:defcstruct IPLSource
  (position IPLVector3)
  (ahead IPLVector3)
  (up IPLVector3)
  (right IPLVector3)
  (directivity IPLDirectivity)
  (distanceAttenuationModel IPLDistanceAttenuationModel)
  (airAbsorptionModel IPLAirAbsorptionModel))

(cffi:defcfun ("iplGetDirectSoundPath" iplGetDirectSoundPath) IPLDirectSoundPath
  (environment :pointer)
  (listenerPosition IPLVector3)
  (listenerAhead IPLVector3)
  (listenerUp IPLVector3)
  (source IPLSource)
  (sourceRadius :float)
  (numSamples :int)
  (occlusionMode IPLDirectOcclusionMode)
  (occlusionMethod IPLDirectOcclusionMethod))

(cffi:defcstruct IPLDirectSoundEffectOptions
  (applyDistanceAttenuation IPLbool)
  (applyAirAbsorption IPLbool)
  (applyDirectivity IPLbool)
  (directOcclusionMode IPLDirectOcclusionMode))

(cffi:defcfun ("iplCreateDirectSoundEffect" iplCreateDirectSoundEffect) IPLerror
  (inputFormat IPLAudioFormat)
  (outputFormat IPLAudioFormat)
  (renderingSettings IPLRenderingSettings)
  (effect :pointer))

(cffi:defcfun ("iplDestroyDirectSoundEffect" iplDestroyDirectSoundEffect) :void
  (effect :pointer))

(cffi:defcfun ("iplApplyDirectSoundEffect" iplApplyDirectSoundEffect) :void
  (effect :pointer)
  (inputAudio IPLAudioBuffer)
  (directSoundPath IPLDirectSoundPath)
  (options IPLDirectSoundEffectOptions)
  (outputAudio IPLAudioBuffer))

(cffi:defcfun ("iplFlushDirectSoundEffect" iplFlushDirectSoundEffect) :void
  (effect :pointer))

(cffi:defcenum IPLBakedDataType
  :IPL_BAKEDDATATYPE_STATICSOURCE
  :IPL_BAKEDDATATYPE_STATICLISTENER
  :IPL_BAKEDDATATYPE_REVERB)

(cffi:defcstruct IPLBakedDataIdentifier
  (identifier :int)
  (type IPLBakedDataType))

(cffi:defcfun ("iplCreateConvolutionEffect" iplCreateConvolutionEffect) IPLerror
  (renderer :pointer)
  (identifier IPLBakedDataIdentifier)
  (simulationType IPLSimulationType)
  (inputFormat IPLAudioFormat)
  (outputFormat IPLAudioFormat)
  (effect :pointer))

(cffi:defcfun ("iplDestroyConvolutionEffect" iplDestroyConvolutionEffect) :void
  (effect :pointer))

(cffi:defcfun ("iplSetConvolutionEffectIdentifier" iplSetConvolutionEffectIdentifier) :void
  (effect :pointer)
  (identifier IPLBakedDataIdentifier))

(cffi:defcfun ("iplSetDryAudioForConvolutionEffect" iplSetDryAudioForConvolutionEffect) :void
  (effect :pointer)
  (source IPLSource)
  (dryAudio IPLAudioBuffer))

(cffi:defcfun ("iplGetWetAudioForConvolutionEffect" iplGetWetAudioForConvolutionEffect) :void
  (effect :pointer)
  (listenerPosition IPLVector3)
  (listenerAhead IPLVector3)
  (listenerUp IPLVector3)
  (wetAudio IPLAudioBuffer))

(cffi:defcfun ("iplGetMixedEnvironmentalAudio" iplGetMixedEnvironmentalAudio) :void
  (renderer :pointer)
  (listenerPosition IPLVector3)
  (listenerAhead IPLVector3)
  (listenerUp IPLVector3)
  (mixedWetAudio IPLAudioBuffer))

(cffi:defcfun ("iplFlushConvolutionEffect" iplFlushConvolutionEffect) :void
  (effect :pointer))

(cffi:defcenum IPLProbePlacement
  :IPL_PLACEMENT_CENTROID
  :IPL_PLACEMENT_OCTREE
  :IPL_PLACEMENT_UNIFORMFLOOR)

(cffi:defcstruct IPLProbePlacementParams
  (placement IPLProbePlacement)
  (spacing :float)
  (heightAboveFloor :float)
  (maxOctreeTriangles :int)
  (maxOctreeDepth :int))

(cffi:defcfun ("iplCreateProbeBox" iplCreateProbeBox) IPLerror
  (context :pointer)
  (scene :pointer)
  (boxLocalToWorldTransform :pointer)
  (placementParams IPLProbePlacementParams)
  (progressCallback :pointer)
  (probeBox :pointer))

(cffi:defcfun ("iplDestroyProbeBox" iplDestroyProbeBox) :void
  (probeBox :pointer))

(cffi:defcfun ("iplGetProbeSpheres" iplGetProbeSpheres) :int
  (probeBox :pointer)
  (probeSpheres :pointer))

(cffi:defcfun ("iplSaveProbeBox" iplSaveProbeBox) :int
  (probeBox :pointer)
  (data :pointer))

(cffi:defcfun ("iplLoadProbeBox" iplLoadProbeBox) IPLerror
  (context :pointer)
  (data :pointer)
  (size :int)
  (probeBox :pointer))

(cffi:defcfun ("iplCreateProbeBatch" iplCreateProbeBatch) IPLerror
  (context :pointer)
  (probeBatch :pointer))

(cffi:defcfun ("iplDestroyProbeBatch" iplDestroyProbeBatch) :void
  (probeBatch :pointer))

(cffi:defcfun ("iplAddProbeToBatch" iplAddProbeToBatch) :void
  (probeBatch :pointer)
  (probeBox :pointer)
  (probeIndex :int))

(cffi:defcfun ("iplFinalizeProbeBatch" iplFinalizeProbeBatch) :void
  (probeBatch :pointer))

(cffi:defcfun ("iplSaveProbeBatch" iplSaveProbeBatch) :int
  (probeBatch :pointer)
  (data :pointer))

(cffi:defcfun ("iplLoadProbeBatch" iplLoadProbeBatch) IPLerror
  (context :pointer)
  (data :pointer)
  (size :int)
  (probeBatch :pointer))

(cffi:defcfun ("iplCreateProbeManager" iplCreateProbeManager) IPLerror
  (context :pointer)
  (probeManager :pointer))

(cffi:defcfun ("iplDestroyProbeManager" iplDestroyProbeManager) :void
  (probeManager :pointer))

(cffi:defcfun ("iplAddProbeBatch" iplAddProbeBatch) :void
  (probeManager :pointer)
  (probeBatch :pointer))

(cffi:defcfun ("iplRemoveProbeBatch" iplRemoveProbeBatch) :void
  (probeManager :pointer)
  (probeBatch :pointer))

(cffi:defcstruct IPLBakingSettings
  (bakeParametric IPLbool)
  (bakeConvolution IPLbool)
  (irDurationForBake :float))

(cffi:defcfun ("iplBakeReverb" iplBakeReverb) :void
  (environment :pointer)
  (probeBox :pointer)
  (bakingSettings IPLBakingSettings)
  (progressCallback :pointer))

(cffi:defcfun ("iplBakePropagation" iplBakePropagation) :void
  (environment :pointer)
  (probeBox :pointer)
  (sourceInfluence IPLSphere)
  (sourceIdentifier IPLBakedDataIdentifier)
  (bakingSettings IPLBakingSettings)
  (progressCallback :pointer))

(cffi:defcfun ("iplBakeStaticListener" iplBakeStaticListener) :void
  (environment :pointer)
  (probeBox :pointer)
  (listenerInfluence IPLSphere)
  (listenerIdentifier IPLBakedDataIdentifier)
  (bakingSettings IPLBakingSettings)
  (progressCallback :pointer))

(cffi:defcfun ("iplCancelBake" iplCancelBake) :void)

(cffi:defcfun ("iplDeleteBakedDataByIdentifier" iplDeleteBakedDataByIdentifier) :void
  (probeBox :pointer)
  (identifier IPLBakedDataIdentifier))

(cffi:defcfun ("iplGetBakedDataSizeByIdentifier" iplGetBakedDataSizeByIdentifier) :int
  (probeBox :pointer)
  (identifier IPLBakedDataIdentifier))


